# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, "8.0"
use_frameworks!

target 'TopApps' do

pod 'SwiftyJSON', '~> 2.2.0'
end

target 'TopAppsTests' do

end

